### ISSUE TITLE
Wow this thing is neat!

### ISSUE THREAD

**Issue by symgryph** [kuba2k2/alpine-home-assistant#2]
I just installed it. Only one little hickup, I had to manually setup the key path for the system to work. After that (other than needing to add my new user to the abuild group) everything works fine.

A few questions, where in heavens name does the docker stuff come from? Or is it part of the HomeAssistant python magic? 

This looks like all kinds of evil network sorcery, any good explanations as to how all the veth's are passing layer 2 stuff to docker? I used to use pipework to do this, but this is the first time I have seen it working w/o that tool.

VERY nice script. I use on my pi4 (with alpine on it if you can believe that!) running f2fs. If you are ever interested in the image, I would be happy to provide. I fix lots of pi4 stupdisms like the network only doing 200mbps (I got it up to 900) due to cpu throttling.

Anyways THANKS for a great project. I can use my nice alpine w/o having to use evil debian.

**Comment by kuba2k2** [comment]
Hi

I'm using it on an Allwinner H2 box, with a custom kernel to replace the stock software. I also have alpine on pi3b, but without HA as I don't need it. Main reason for that is alpine is much faster and slimmer.

Not sure what you mean with the network questions. I think it's standard docker proxying stuff, or host mode networks. 

About the manual setup, what key path do you mean exactly? I think I mentioned adding the user to abuild.

I'm glad you found it useful anyway 😀
