### ISSUE TITLE
Problem with rshared on fstab for mount /

### ISSUE THREAD

**Issue by hugoleosp** [kuba2k2/alpine-home-assistant#5]
I've been trying to install HA for quite a few time now and I was following your tutorial and I wasn't getting any error from the steps provided but HA wasn't installing .. only one image on docker could be seen .. then checking the docker.log I was getting the following error:

`"Handler for POST /v1.45/containers/hassio_supervisor/start returned error: path /usr/share/hassio is mounted on / but it is not a shared or slave mount"`

And googling a solution I found that for an unknown reason my / wasn't being mounted with the shared flag even it's written in the /etc/fstab ... then I followed this guide and it worked:

https://ixday.github.io/post/shared_mount/

All I need to do was manually share the / with the following command:
`mount --make-shared /`

Remove all the packages and reinstall them again .. 
and it worked =D

Thank you for all your effort .. thank you so much =D

**Comment by kuba2k2** [comment]
This might be due to non standard configuration on your Alpine Linux. I'm using the same packages, it gets mounted by fstab and the flag is there.

**Comment by hugoleosp** [comment]
It seems a non standard configuration like @kuba2k2 mentioned .. but I just followed the installation guide from Alpine official website. But maybe it's because it's installed as a virtual machine... but following the guide with the solution seems to have worked even after a reboot... so I just want to leave here in case anyone else face the same issue ..

**Comment by kuba2k2** [comment]
Did you reboot after adding the rshared flag to fstab? Commands like mount don't propagate after reboots. If it still works after a reboot, it means that the flag in fstab works. So you probably didn't reboot after adding it.
